### ISSUE TITLE
Implement unit tests for the UI

### ISSUE THREAD

**Issue by gsilvapt** [stayawayinesctec/authcode-ui#21]
As stated in [the main Stayaway application repository](https://github.com/stayawayinesctec/stayaway-app/issues/7), automated tests are of great importance to permit contributions.

**Comment by fntneves** [comment]
Thank you for pointing this out. However, this repository is now aimed strictly at allowing everyone to fully reproduce a complete system and understand how it works. This very functionality — code generation UI — in STAYAWAY COVID has been integrated in a larger system. Therefore, we don't expect that any community contribution to this project finds its way to production.

**Comment by hugotavares** [comment]
I fully agree with @gsilvapt on the need for unit tests against the app's UI.

**UI tests are also one of the most relevant ways to assure the software is written and executed according to its specification**. This definition is a _de facto_ for everyone who gets the [entry-level certification from ISTQB](https://www.istqb.org/certification-path-root/foundation-level-2018.html#syllabus) and should motivate the concern for such procedures.

If still not within this project then at the mean least kindly **refer the project where specifically they should be added**,
